# Slim Configuration
slimSettings:
  webtoken:
    enabled: true
    issuer: http://localhost:3000
    validUrlPatterns: 
        - 
            '^https?://.*'
        - 
            '^file:///.*'
    signingAlgorithm: 'HS256'
    appRegistry: 
        - 
            id: 'http://localhost:3000/admin'
            name: 'Test Application 1'
            description: 'This is only a test.'
            contact:
                name: 'John Smith'
                phone: '555-555-5555'
                email: 'jsmith@example.edu'
                department: 'Information Technology'
            attributes: 
            - 
                'GivenName'
            - 
                'Surname'
            - 
                'EduPersonPrimaryAffiliation'
            - 
                'mail'
            sharedSecret: 'geZHfW7mUmZhcfWFpqswN4F7zAEBxALc'     
  # Display error messages to the user when an exception is thrown
  displayErrorDetails: true
  # Use Monolog for logging
  logger:
    path: ../logs/application.log
    name: slimSkeleton
    level: info
  # Use Twig for templating
  view:
    template_path: ../templates
    twig:
      cache: ../cache
      debug: true
      # Rebuild views whenever they change
      auto_reload: true
      # Auto escape HTML data
      autoescape: true
      # Ignore invalid variables instead of throwing an exception
      strict_variables: false
  authentication:
    # Use CAS for authentication
    cas:
      environment: development
    token:
      app_id: USF-IT/ARM-jack
      token_url: http://localhost:3000/
    # AuthN/AuthZ Map
    interceptUrlMap:
      GET:
        '/health_check': # Health check is allowed without authentication
          authN: permitAll
          authZ: permitAll
        '/views/home': # Allow home view without authentication
          authN: permitAll
          authZ: permitAll
        GET:
        '/views/admin': # Restrict admin page to logged in users with Auth token
          authN: token
          authZ: permitAll
        '/**': # All other pages require CAS
          authN: CAS
          authZ: permitAll
        '/login': # Allow the login page without authentication
          authN: permitAll
          authZ: permitAll
        '/': # Allow the home page without authentication
          authN: permitAll
          authZ: permitAll
      POST:
        '/**':
          authN: CAS
          authZ: permitAll
      PUT:
        '/**':
          authN: denyAll
          authZ: denyAll
      DELETE:
        '/**':
          authN: denyAll
          authZ: denyAll
